export const ENDPOINTS = {
  health: "/health",
  ready: "/health/ready",
  authLogin: "/api/cms/auth/login",
  authRefresh: "/api/cms/auth/refresh",
  authLogout: "/api/cms/auth/logout",
  dashboardSummary: "/api/cms/dashboard/summary",
  cmsHome: "/api/cms/home",
  cmsSkills: "/api/cms/skills",
  cmsProjects: "/api/cms/projects",
  cmsProjectsHeader: "/api/cms/projects/header",
  cmsProjectsHeaderImage: "/api/cms/projects/header/showcase-image",
  cmsProject: (slug: string) => `/api/cms/projects/${slug}`,
  cmsProjectPublish: (slug: string) => `/api/cms/projects/${slug}/publish`,
  cmsProjectsReorder: "/api/cms/projects/reorder",
  cmsBlogs: "/api/cms/blogs",
  cmsBlog: (slug: string) => `/api/cms/blogs/${slug}`,
  cmsBlogPublish: (slug: string) => `/api/cms/blogs/${slug}/publish`,
  cmsBlogBlocks: (slug: string) => `/api/cms/blogs/${slug}/blocks`,
  cmsBlogBlocksReorder: (slug: string) => `/api/cms/blogs/${slug}/blocks/reorder`,
  cmsBlogBlock: (slug: string, blockId: string) => `/api/cms/blogs/${slug}/blocks/${blockId}`,
  cmsContact: "/api/cms/contact",
  cmsMessages: "/api/cms/messages",
  cmsMessageStatus: (id: string) => `/api/cms/messages/${id}/status`,
  cmsMeetingRequests: "/api/cms/meeting-requests",
  cmsMeetingRequestStatus: (id: string) => `/api/cms/meeting-requests/${id}/status`,
  cmsMediaSignUpload: "/api/cms/media/sign-upload",
  cmsMedia: "/api/cms/media",
  cmsMediaAsset: (id: string) => `/api/cms/media/${id}`,
  cmsExperience: "/api/cms/experience",
  cmsExperienceItem: (id: string) => `/api/cms/experience/${id}`,
  cmsExperienceReorder: "/api/cms/experience/reorder",
  cmsAbout: "/api/cms/about",
  cmsSettings: "/api/cms/settings",
  cmsSeo: "/api/cms/seo",
  cmsSeoItem: (id: string) => `/api/cms/seo/${id}`,
  cmsUsers: "/api/cms/users",
  cmsUser: (id: string) => `/api/cms/users/${id}`,
  cmsRoles: "/api/cms/roles",
  cmsRole: (id: string) => `/api/cms/roles/${id}`,
  cmsAuditLogs: "/api/cms/audit-logs",
} as const;
