export const keys = {
  dashboard: ["dashboard"] as const,
  home: ["home"] as const,
  skills: ["skills"] as const,
  projects: ["projects"] as const,
  projectsHeader: ["projects-header"] as const,
  blogs: ["blogs"] as const,
  contact: ["contact"] as const,
  messages: ["messages"] as const,
  meetingRequests: ["meeting-requests"] as const,
  media: ["media"] as const,
  experience: ["experience"] as const,
  about: ["about"] as const,
  settings: ["settings"] as const,
  seo: ["seo"] as const,
  users: ["users"] as const,
  roles: ["roles"] as const,
  auditLogs: ["audit-logs"] as const,
};
